### ISSUE TITLE
PA review tasks

### ISSUE THREAD

**Issue by NyxinU** [NyxinU/Treat_Yourself#9]

**Comment by evhumphrey** [comment]
I recommend redirecting to /tasks when logging in instead of /app (because there's nothing there)

**Comment by evhumphrey** [comment]
Also on heroku, there's no way to update tasks?

**Comment by NyxinU** [comment]
oops i forgot to reply, sorry! tasks should be functional now

**Comment by evhumphrey** [comment]
👍

**Comment by evhumphrey** [comment]
Wait, when clicking on a task, add active styling

**Comment by NyxinU** [comment]
font is now blue when active

**Comment by evhumphrey** [comment]
Bug: how to view complete vs incomplete tasks

**Comment by evhumphrey** [comment]
^ I think it's an issue of not toggling the "Complete" button text
